name: Deploy to Server

on:
  push:
    branches:
      - production/githubAction

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: appleboy/ghaction-ssh@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            # 1. Create the directory on the server (if it doesn't exist)
            mkdir -p ~/deployWallet

            # 2. Copy the files from the GitHub Actions runner to the server
            rsync -avz $GITHUB_WORKSPACE/ ~/deployWallet/

            # 3. Navigate to the directory
            cd ~/deployWallet/wallet

            # 4. Run Docker Compose (assuming docker-compose.yml is in the repo's root)
            docker-compose up -d --build
