name: Deploy to Server

on:
  push:
    branches:
      - production/githubAction

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main # Updated to the latest version
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # Changed 'key' to 'SSH_PRIVATE_KEY' and using secret name as suggested
          REMOTE_HOST: ${{ secrets.SERVER_IP }} # Changed 'host' to 'REMOTE_HOST'
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }} # Changed 'username' to 'REMOTE_USER'
          SOURCE: "." # Deploying the entire workspace, you can adjust SOURCE and TARGET as needed
          TARGET: "~/deployWallet" # Changed target directory to ~/deployWallet based on your script
          SCRIPT_BEFORE: "ls" # Added SCRIPT_BEFORE to force known_hosts update - workaround for "Permission denied" error
          SCRIPT_AFTER:
            | # Moved your script to SCRIPT_AFTER for better structure and clarity
            cd ~/deployWallet
            npx prisma generate
            export NEXT_PUBLIC_API_ENDPOINT="${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}"
            export NEXT_PUBLIC_API_KEY="${{ secrets.NEXT_PUBLIC_API_KEY }}"
            export NEXT_PUBLIC_SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
            export NEXT_PUBLIC_SUPABASE_ANON_KEY="${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}"
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export DIRECT_URL="${{ secrets.DIRECT_URL }}"
            export NEXT_PUBLIC_EXP_BLOCKSCOUNT_URL="${{ secrets.NEXT_PUBLIC_EXP_BLOCKSCOUNT_URL }}"
            export ENGINE_BASE_URL="${{ secrets.ENGINE_BASE_URL }}"
            export ENGINE_X_BACKEND_WALLET_ADDRESS="${{ secrets.ENGINE_X_BACKEND_WALLET_ADDRESS }}"
            export ENGINE_AUTHORIZATION_TOKEN="${{ secrets.ENGINE_AUTHORIZATION_TOKEN }}"
            export ENGINE_CHAIN_ID="${{ secrets.ENGINE_CHAIN_ID }}"
            docker compose -f docker-compose.yml up -d --build
